# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.define 'lab2'
  
  # use preconfigured box to start mach faster
  config.vm.box = 'https://dl.dropboxusercontent.com/u/102236368/lab2-1.0.box'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 512
  end

  config.vm.provision :shell, path: "install.sh" # build in into box

  node_group = 1
  if ENV['NODE_GROUP']
    node_group = ENV['NODE_GROUP']
    puts "Node group: #{node_group}"
  else 
    puts "Warning!!! Using default node group: #{node_group}"
    puts "Use export to set node goup: 'export NODE_GROUP=5'"
  end

  (0 .. 2).each do |node_num|
    i = "#{node_group}#{node_num}"
    config.vm.define "node-#{i}" do |node|
      node.vm.network "public_network", ip: "192.168.1.1#{i}", bridge: "en0: Wi-Fi (AirPort)"
      node.vm.hostname = "node-#{i}"

      node.vm.provision "kill", type: "shell", 
        inline: "/bin/bash -c 'sudo kill -9 $(lsof -t -i:8239); exit 0'"
      node.vm.provision "shell", 
        inline: "rm -f /home/vagrant/node.log"
      node.vm.provision "shell",
        inline: "echo hello from node-#{i}"
      node.vm.provision :shell,  
        path: "run.sh"
      #, run: "always"
    end
  end


end

